import type { Metadata } from "next";
import "./globals.css";
import SidebarWrapper from "@/components/SidebarWrapper";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <div className="flex max-w-6xl mx-auto">
            <SidebarWrapper />
            {children}
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
